version: "3.8"

services:
  backend:
    build:
      context: ../.. # Points to solution root
      dockerfile: Docker/Backend_Docker/Dockerfile
    container_name: Dirasati-Backend
    ports:
      - "5080:8080"
      - "5081:5081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/data/dirasatiDb.db
      - Email__SenderEmail=mohamed@dirasati.org
      - Email__SenderName=Dirasati
      - Email__Host=smtp4dev_mail
      - Email__Port=25
      - FrontendUrl=http://localhost:5173
    volumes:
      - ./data:/data # Map SQLite file to host
    networks:
      - app-network
    restart: always
    depends_on:
      - mailserver

  mailserver:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev_mail
    ports:
      - "5025:25"
      - "6080:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
