version: "3.8"

services:
  backend:
    build: .
    container_name: Dirasati-Backend
    ports:
      - "5080:8080"
      - "5081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=dirasatiDb.db
    restart: always
